#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-scm
Version  : 1.8
Release  : 9
URL      : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.jar
Source1  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-scm-plugin/1.9.2/maven-scm-plugin-1.9.2.jar
Source2  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-scm-plugin/1.9.2/maven-scm-plugin-1.9.2.pom
Source3  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-scm-plugin/1.9.4/maven-scm-plugin-1.9.4.jar
Source4  : https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-scm-plugin/1.9.4/maven-scm-plugin-1.9.4.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.pom
Source6  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.9.2/maven-scm-api-1.9.2.jar
Source7  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.9.2/maven-scm-api-1.9.2.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.9.4/maven-scm-api-1.9.4.jar
Source9  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-api/1.9.4/maven-scm-api-1.9.4.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2/maven-scm-manager-plexus-1.9.2.jar
Source11  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2/maven-scm-manager-plexus-1.9.2.pom
Source12  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4/maven-scm-manager-plexus-1.9.4.jar
Source13  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4/maven-scm-manager-plexus-1.9.4.pom
Source14  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-managers/1.9.2/maven-scm-managers-1.9.2.pom
Source15  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-managers/1.9.4/maven-scm-managers-1.9.4.pom
Source16  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2/maven-scm-provider-bazaar-1.9.2.jar
Source17  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2/maven-scm-provider-bazaar-1.9.2.pom
Source18  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4/maven-scm-provider-bazaar-1.9.4.jar
Source19  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4/maven-scm-provider-bazaar-1.9.4.pom
Source20  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2/maven-scm-provider-clearcase-1.9.2.jar
Source21  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2/maven-scm-provider-clearcase-1.9.2.pom
Source22  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4/maven-scm-provider-clearcase-1.9.4.jar
Source23  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4/maven-scm-provider-clearcase-1.9.4.pom
Source24  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2/maven-scm-provider-cvs-commons-1.9.2.jar
Source25  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2/maven-scm-provider-cvs-commons-1.9.2.pom
Source26  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4/maven-scm-provider-cvs-commons-1.9.4.jar
Source27  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4/maven-scm-provider-cvs-commons-1.9.4.pom
Source28  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2/maven-scm-provider-cvsexe-1.9.2.jar
Source29  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2/maven-scm-provider-cvsexe-1.9.2.pom
Source30  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4/maven-scm-provider-cvsexe-1.9.4.jar
Source31  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4/maven-scm-provider-cvsexe-1.9.4.pom
Source32  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2/maven-scm-provider-git-commons-1.9.2.jar
Source33  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2/maven-scm-provider-git-commons-1.9.2.pom
Source34  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4/maven-scm-provider-git-commons-1.9.4.jar
Source35  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4/maven-scm-provider-git-commons-1.9.4.pom
Source36  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2/maven-scm-provider-gitexe-1.9.2.jar
Source37  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2/maven-scm-provider-gitexe-1.9.2.pom
Source38  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4/maven-scm-provider-gitexe-1.9.4.jar
Source39  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4/maven-scm-provider-gitexe-1.9.4.pom
Source40  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-hg/1.9.2/maven-scm-provider-hg-1.9.2.jar
Source41  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-hg/1.9.2/maven-scm-provider-hg-1.9.2.pom
Source42  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-hg/1.9.4/maven-scm-provider-hg-1.9.4.jar
Source43  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-hg/1.9.4/maven-scm-provider-hg-1.9.4.pom
Source44  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2/maven-scm-provider-perforce-1.9.2.jar
Source45  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2/maven-scm-provider-perforce-1.9.2.pom
Source46  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4/maven-scm-provider-perforce-1.9.4.jar
Source47  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4/maven-scm-provider-perforce-1.9.4.pom
Source48  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2/maven-scm-provider-starteam-1.9.2.jar
Source49  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2/maven-scm-provider-starteam-1.9.2.pom
Source50  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4/maven-scm-provider-starteam-1.9.4.jar
Source51  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4/maven-scm-provider-starteam-1.9.4.pom
Source52  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svn-commons/1.8/maven-scm-provider-svn-commons-1.8.pom
Source53  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2/maven-scm-provider-svn-commons-1.9.2.jar
Source54  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2/maven-scm-provider-svn-commons-1.9.2.pom
Source55  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4/maven-scm-provider-svn-commons-1.9.4.jar
Source56  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4/maven-scm-provider-svn-commons-1.9.4.pom
Source57  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2/maven-scm-provider-svnexe-1.9.2.jar
Source58  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2/maven-scm-provider-svnexe-1.9.2.pom
Source59  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4/maven-scm-provider-svnexe-1.9.4.jar
Source60  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4/maven-scm-provider-svnexe-1.9.4.pom
Source61  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-cvs/1.9.2/maven-scm-providers-cvs-1.9.2.pom
Source62  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-cvs/1.9.4/maven-scm-providers-cvs-1.9.4.pom
Source63  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-git/1.9.2/maven-scm-providers-git-1.9.2.pom
Source64  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-git/1.9.4/maven-scm-providers-git-1.9.4.pom
Source65  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-svn/1.8/maven-scm-providers-svn-1.8.pom
Source66  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-svn/1.9.2/maven-scm-providers-svn-1.9.2.pom
Source67  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers-svn/1.9.4/maven-scm-providers-svn-1.9.4.pom
Source68  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers/1.8/maven-scm-providers-1.8.pom
Source69  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers/1.9.2/maven-scm-providers-1.9.2.pom
Source70  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm-providers/1.9.4/maven-scm-providers-1.9.4.pom
Source71  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm/1.8/maven-scm-1.8.pom
Source72  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm/1.9.2/maven-scm-1.9.2.pom
Source73  : https://repo1.maven.org/maven2/org/apache/maven/scm/maven-scm/1.9.4/maven-scm-1.9.4.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-scm-data = %{version}-%{release}
Requires: mvn-maven-scm-license = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-scm package.
Group: Data

%description data
data components for the mvn-maven-scm package.


%package license
Summary: license components for the mvn-maven-scm package.
Group: Default

%description license
license components for the mvn-maven-scm package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-maven-scm
cp LICENSE %{buildroot}/usr/share/package-licenses/mvn-maven-scm/LICENSE
cp NOTICE %{buildroot}/usr/share/package-licenses/mvn-maven-scm/NOTICE
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.8
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.2
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.2/maven-scm-plugin-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.2
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.2/maven-scm-plugin-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.4
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.4/maven-scm-plugin-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.4
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.4/maven-scm-plugin-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.8
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.2/maven-scm-api-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.2/maven-scm-api-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.4
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.4/maven-scm-api-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.4
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.4/maven-scm-api-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2/maven-scm-manager-plexus-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2/maven-scm-manager-plexus-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4/maven-scm-manager-plexus-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4/maven-scm-manager-plexus-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-managers/1.9.2
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-managers/1.9.2/maven-scm-managers-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-managers/1.9.4
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-managers/1.9.4/maven-scm-managers-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2/maven-scm-provider-bazaar-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2/maven-scm-provider-bazaar-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4/maven-scm-provider-bazaar-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4/maven-scm-provider-bazaar-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2/maven-scm-provider-clearcase-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2/maven-scm-provider-clearcase-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4/maven-scm-provider-clearcase-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4/maven-scm-provider-clearcase-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2/maven-scm-provider-cvs-commons-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2/maven-scm-provider-cvs-commons-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4/maven-scm-provider-cvs-commons-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4/maven-scm-provider-cvs-commons-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2/maven-scm-provider-cvsexe-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2/maven-scm-provider-cvsexe-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4/maven-scm-provider-cvsexe-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4/maven-scm-provider-cvsexe-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2/maven-scm-provider-git-commons-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2/maven-scm-provider-git-commons-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4/maven-scm-provider-git-commons-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4/maven-scm-provider-git-commons-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2/maven-scm-provider-gitexe-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2/maven-scm-provider-gitexe-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4/maven-scm-provider-gitexe-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4/maven-scm-provider-gitexe-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.2
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.2/maven-scm-provider-hg-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.2
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.2/maven-scm-provider-hg-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.4
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.4/maven-scm-provider-hg-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.4
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.4/maven-scm-provider-hg-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2/maven-scm-provider-perforce-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2/maven-scm-provider-perforce-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4/maven-scm-provider-perforce-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4/maven-scm-provider-perforce-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2/maven-scm-provider-starteam-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2/maven-scm-provider-starteam-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4/maven-scm-provider-starteam-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4/maven-scm-provider-starteam-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.8
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.8/maven-scm-provider-svn-commons-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2/maven-scm-provider-svn-commons-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2/maven-scm-provider-svn-commons-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4/maven-scm-provider-svn-commons-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4
cp %{SOURCE56} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4/maven-scm-provider-svn-commons-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2
cp %{SOURCE57} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2/maven-scm-provider-svnexe-1.9.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2
cp %{SOURCE58} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2/maven-scm-provider-svnexe-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4
cp %{SOURCE59} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4/maven-scm-provider-svnexe-1.9.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4
cp %{SOURCE60} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4/maven-scm-provider-svnexe-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-cvs/1.9.2
cp %{SOURCE61} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-cvs/1.9.2/maven-scm-providers-cvs-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-cvs/1.9.4
cp %{SOURCE62} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-cvs/1.9.4/maven-scm-providers-cvs-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-git/1.9.2
cp %{SOURCE63} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-git/1.9.2/maven-scm-providers-git-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-git/1.9.4
cp %{SOURCE64} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-git/1.9.4/maven-scm-providers-git-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.8
cp %{SOURCE65} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.8/maven-scm-providers-svn-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.9.2
cp %{SOURCE66} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.9.2/maven-scm-providers-svn-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.9.4
cp %{SOURCE67} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.9.4/maven-scm-providers-svn-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.8
cp %{SOURCE68} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.8/maven-scm-providers-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.9.2
cp %{SOURCE69} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.9.2/maven-scm-providers-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.9.4
cp %{SOURCE70} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.9.4/maven-scm-providers-1.9.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.8
cp %{SOURCE71} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.8/maven-scm-1.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.9.2
cp %{SOURCE72} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.9.2/maven-scm-1.9.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.9.4
cp %{SOURCE73} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.9.4/maven-scm-1.9.4.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.2/maven-scm-plugin-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.2/maven-scm-plugin-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.4/maven-scm-plugin-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/plugins/maven-scm-plugin/1.9.4/maven-scm-plugin-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.8/maven-scm-api-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.2/maven-scm-api-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.2/maven-scm-api-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.4/maven-scm-api-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-api/1.9.4/maven-scm-api-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2/maven-scm-manager-plexus-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.2/maven-scm-manager-plexus-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4/maven-scm-manager-plexus-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-manager-plexus/1.9.4/maven-scm-manager-plexus-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-managers/1.9.2/maven-scm-managers-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-managers/1.9.4/maven-scm-managers-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2/maven-scm-provider-bazaar-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.2/maven-scm-provider-bazaar-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4/maven-scm-provider-bazaar-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-bazaar/1.9.4/maven-scm-provider-bazaar-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2/maven-scm-provider-clearcase-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.2/maven-scm-provider-clearcase-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4/maven-scm-provider-clearcase-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-clearcase/1.9.4/maven-scm-provider-clearcase-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2/maven-scm-provider-cvs-commons-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.2/maven-scm-provider-cvs-commons-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4/maven-scm-provider-cvs-commons-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvs-commons/1.9.4/maven-scm-provider-cvs-commons-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2/maven-scm-provider-cvsexe-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.2/maven-scm-provider-cvsexe-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4/maven-scm-provider-cvsexe-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-cvsexe/1.9.4/maven-scm-provider-cvsexe-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2/maven-scm-provider-git-commons-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.2/maven-scm-provider-git-commons-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4/maven-scm-provider-git-commons-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-git-commons/1.9.4/maven-scm-provider-git-commons-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2/maven-scm-provider-gitexe-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.2/maven-scm-provider-gitexe-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4/maven-scm-provider-gitexe-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-gitexe/1.9.4/maven-scm-provider-gitexe-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.2/maven-scm-provider-hg-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.2/maven-scm-provider-hg-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.4/maven-scm-provider-hg-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-hg/1.9.4/maven-scm-provider-hg-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2/maven-scm-provider-perforce-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.2/maven-scm-provider-perforce-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4/maven-scm-provider-perforce-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-perforce/1.9.4/maven-scm-provider-perforce-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2/maven-scm-provider-starteam-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.2/maven-scm-provider-starteam-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4/maven-scm-provider-starteam-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-starteam/1.9.4/maven-scm-provider-starteam-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.8/maven-scm-provider-svn-commons-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2/maven-scm-provider-svn-commons-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.2/maven-scm-provider-svn-commons-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4/maven-scm-provider-svn-commons-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svn-commons/1.9.4/maven-scm-provider-svn-commons-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2/maven-scm-provider-svnexe-1.9.2.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.2/maven-scm-provider-svnexe-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4/maven-scm-provider-svnexe-1.9.4.jar
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-provider-svnexe/1.9.4/maven-scm-provider-svnexe-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-cvs/1.9.2/maven-scm-providers-cvs-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-cvs/1.9.4/maven-scm-providers-cvs-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-git/1.9.2/maven-scm-providers-git-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-git/1.9.4/maven-scm-providers-git-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.8/maven-scm-providers-svn-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.9.2/maven-scm-providers-svn-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers-svn/1.9.4/maven-scm-providers-svn-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.8/maven-scm-providers-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.9.2/maven-scm-providers-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm-providers/1.9.4/maven-scm-providers-1.9.4.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.8/maven-scm-1.8.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.9.2/maven-scm-1.9.2.pom
/usr/share/java/.m2/repository/org/apache/maven/scm/maven-scm/1.9.4/maven-scm-1.9.4.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-maven-scm/LICENSE
/usr/share/package-licenses/mvn-maven-scm/NOTICE
